class UnknownActor : Actor { states { Spawn: #### # 0 NoDelay { console.printf('Unknown actor or visual thinker'); Destroy(); } stop; } }

class ReplaceAllActors : Eventhandler
{
	override void CheckReplacement (ReplaceEvent e)
	{
		switch (e.replacee.GetClassName())
		{
			// Chex
            case 'ChexBlueCard':
            case 'ChexYellowCard':
            case 'Zorchpack':
            case 'FlemoidusBipedicus':
            case 'ChexRedCard':
            case 'PhasingZorchPack':
            case 'ChexTallFlower2':
            case 'ChexTallFlower':
            case 'ChexCavernStalagmite':
            case 'ChexSubmergedPlant':
            case 'ChexCavernColumn':
            case 'ChexMineCart':
            case 'ChexChemicalFlask':
            case 'ChexGasTank':
            case 'ChexFlagOnPole':
            case 'ChexChemicalBurner':
            case 'ChexOrangeTree':
            case 'ChexSlimeFountain':
            case 'ChexCivilian1':
            case 'ChexAppleTree':
            case 'ChexSpaceship':
            case 'ChexBananaTree':
            case 'ChexLightColumn':
            case 'ChexCivilian2':
            case 'ChexCivilian3':
            case 'SuperLargeZorcher':
            case 'LargeZorcher':
            case 'RapidZorcher':
            case 'ZorchPropulsor':
            case 'PhasingZorcher':
            case 'SuperBootspork':
            case 'LAZDevice':
            case 'MiniZorchRecharge':
            case 'LargeZorchRecharge':
            case 'PropulsorZorch':
            case 'BowlOfFruit':
            case 'BowlOfVegetables':
            case 'SuperchargeBreakfast':
            case 'GlassOfWater':
            case 'SlimeRepellent':
            case 'ChexArmor':
            case 'SuperChexArmor':
            case 'SlimeProofSuit':
            case 'ComputerAreaMap':
            case 'ChexLandingLight':
            case 'PropulsorZorchPack':
            case 'PhasingZorch':
            case 'MiniZorchPack':
            case 'LargeZorchPack':
            case 'ArmoredFlemoidusBipedicus':
            case 'FlemoidusCycloptisCommonus':
            case 'Flembrane':
            case 'FlemoidusCommonus':
            case 'ChexSoul':
            case 'MiniZorcher':
			
			//Doom
			case 'BlueCard':
			case 'YellowCard':
			case 'SpiderMastermind':
			case 'Backpack':
			case 'ShotgunGuy':
            case 'GibbedMarine':
            case 'GibbedMarineExtra':
            case 'RedCard':
            case 'DeadMarine':
            case 'Cyberdemon':
            case 'CellPack':
            case 'DeadZombieMan':
            case 'DeadShotgunGuy':
            case 'DeadDoomImp':
            case 'DeadDemon':
            case 'DeadCacodemon':
            case 'DeadLostSoul':
            case 'Gibs':
            case 'DeadStick':
            case 'LiveStick':
            case 'HeadOnAStick':
            case 'HeadsOnAStick':
            case 'HeadCandles':
            case 'TallGreenColumn':
            case 'ShortGreenColumn':
            case 'TallRedColumn':
            case 'ShortRedColumn':
            case 'Candlestick':
            case 'Candelabra':
            case 'HeartColumn':
            case 'SkullColumn':
            case 'RedSkull':
            case 'YellowSkull':
            case 'BlueSkull':
            case 'EvilEye':
            case 'FloatingSkull':
            case 'TorchTree':
            case 'BlueTorch':
            case 'GreenTorch':
            case 'RedTorch':
            case 'Stalagtite':
            case 'TechPillar':
            case 'BloodyTwitch':
            case 'Meat2':
            case 'Meat3':
            case 'Meat4':
            case 'Meat5':
            case 'BigTree':
            case 'ShortBlueTorch':
            case 'ShortGreenTorch':
            case 'ShortRedTorch':
            case 'Spectre':
            case 'NonsolidMeat2':
            case 'NonsolidMeat4':
            case 'NonsolidMeat3':
            case 'NonsolidMeat5':
            case 'NonsolidTwitch':
            case 'Archvile':
            case 'ChaingunGuy':
            case 'Revenant':
            case 'Fatso':
            case 'Arachnotron':
            case 'HellKnight':
            case 'BurningBarrel':
            case 'PainElemental':
            case 'CommanderKeen':
            case 'HangNoGuts':
            case 'HangBNoBrain':
            case 'HangTLookingDown':
            case 'HangTSkull':
            case 'HangTLookingUp':
            case 'HangTNoBrain':
            case 'ColonGibs':
            case 'SmallBloodPool':
            case 'BrainStem':
            case 'SuperShotgun':
            case 'Megasphere':
            case 'WolfensteinSS':
            case 'TechLamp':
            case 'TechLamp2':
            case 'BossTarget':
            case 'BossBrain':
            case 'BossEye':
            case 'Shotgun':
            case 'Chaingun':
            case 'RocketLauncher':
            case 'PlasmaRifle':
            case 'Chainsaw':
            case 'BFG9000':
            case 'Clip':
            case 'Shell':
            case 'RocketAmmo':
            case 'Stimpack':
            case 'Medikit':
            case 'Soulsphere':
            case 'HealthBonus':
            case 'ArmorBonus':
            case 'EvilSceptre':
            case 'UnholyBible':
            case 'GreenArmor':
            case 'BlueArmor':
            case 'InvulnerabilitySphere':
            case 'Berserk':
            case 'BlurSphere':
            case 'RadSuit':
            case 'Allmap':
            case 'Column':
            case 'ExplosiveBarrel':
            case 'Infrared':
            case 'RocketBox':
            case 'Cell':
            case 'ClipBox':
            case 'ShellBox':
            case 'DoomImp':
            case 'Demon':
            case 'BaronOfHell':
            case 'Zombieman':
            case 'Cacodemon':
            case 'LostSoul':
            case '$Player5Start':
            case '$Player6Start':
            case '$Player7Start':
            case '$Player8Start':
            case 'Pistol':
            case 'Stalagmite':
            case 'StealthArachnotron':
            case 'StealthArchvile':
            case 'StealthBaron':
            case 'StealthCacodemon':
            case 'StealthChaingunGuy':
            case 'StealthDemon':
            case 'StealthHellKnight':
            case 'StealthDoomImp':
            case 'StealthFatso':
            case 'StealthRevenant':
            case 'StealthShotgunGuy':
            case 'StealthZombieMan':
            case 'ScriptedMarine':
            case 'MarineFist':
            case 'MarineBerserk':
            case 'MarineChainsaw':
            case 'MarinePistol':
            case 'MarineShotgun':
            case 'MarineSSG':
            case 'MarineChaingun':
            case 'MarineRocket':
            case 'MarinePlasma':
            case 'MarineRailgun':
            case 'MarineBFG':
			case 'ID24Fuel':
			case 'ID24FuelTank':
			case 'ID24CalamityBlade':
			case 'ID24Incinerator':
			
			//Heretic
			case 'HereticImpLeader':
            case 'Ironlich':
            case 'Sorcerer1':
            case 'BagOfHolding':
            case 'Minotaur':
            case 'GoldWandAmmo':
            case 'GoldWandHefty':
            case 'MaceAmmo':
            case 'Wizard':
            case 'MaceHefty':
            case 'SkullHang70':
            case 'CrossbowAmmo':
            case 'CrossbowHefty':
            case 'SkullRodAmmo':
            case 'SkullRodHefty':
            case 'PhoenixRodAmmo':
            case 'PhoenixRodHefty':
            case 'SkullHang60':
            case 'SkullHang45':
            case 'SkullHang35':
            case 'SerpentTorch':
            case 'Chandelier':
            case 'SmallPillar':
            case 'ArtiEgg':
            case 'EnchantedShield':
            case 'ArtiSuperHealth':
            case 'ArtiTorch':
            case 'ArtiTimeBomb':
            case 'SuperMap':
            case 'ArtiTeleport':
            case 'StalagmiteSmall':
            case 'StalagmiteLarge':
            case 'StalactiteSmall':
            case 'StalactiteLarge':
            case 'SoundWaterfall':
            case 'SoundWind':
            case 'PodGenerator':
            case 'Barrel':
            case 'MummyLeader':
            case 'MummyLeaderGhost':
            case 'BrownPillar':
            case 'Moss1':
            case 'Moss2':
            case 'WallTorch':
            case 'HangingCorpse':
            case 'TeleGlitterGenerator2':
            case 'Blaster':
            case 'BlasterAmmo':
            case 'BlasterHefty':
            case 'BossSpot':
            case 'Knight':
            case 'KnightGhost':
            case 'HereticImp':
            case 'Mummy':
            case 'MummyGhost':
            case 'Beast':
            case 'KeyGreen':
            case 'TeleGlitterGenerator1':
            case 'ArtiInvisibility':
            case 'FireBrazier':
            case 'KeyBlue':
            case 'KeyYellow':
            case 'CrystalVial':
            case 'ArtiHealth':
            case 'ArtiFly':
            case 'ArtiInvulnerability':
            case 'SilverShield':
            case 'ArtiTomeOfPower':
            case 'Volcano':
            case 'Clink':
            case 'Snake':
            case 'KeyGizmoBlue':
            case 'KeyGizmoGreen':
            case 'KeyGizmoYellow':
            case 'Bridge':
            case 'HereticSoundSequence1':
            case 'HereticSoundSequence2':
            case 'HereticSoundSequence3':
            case 'HereticSoundSequence4':
            case 'HereticSoundSequence5':
            case 'HereticSoundSequence6':
            case 'HereticSoundSequence7':
            case 'HereticSoundSequence8':
            case 'HereticSoundSequence9':
            case 'HereticSoundSequence10':
            case 'Crossbow':
            case 'MaceSpawner':
            case 'PhoenixRod':
            case 'SkullRod':
            case 'Gauntlets':
            case 'Pod':
            case '$Player5Start':
            case '$Player6Start':
            case '$Player7Start':
            case '$Player8Start':
            case 'GoldWand':

			// Hexen
            case 'ZWingedStatue':
            case 'ZRock1':
            case 'ZRock2':
            case 'ZRock3':
            case 'CWeapStaff':
            case 'FWeaponPiece1':
            case 'FWeaponPiece2':
            case 'ZRock4':
            case 'FWeaponPiece3':
            case 'ZChandelier':
            case 'CWeaponPiece1':
            case 'CWeaponPiece2':
            case 'CWeaponPiece3':
            case 'MWeaponPiece1':
            case 'MWeaponPiece2':
            case 'MWeaponPiece3':
            case 'ZTreeDead':
            case 'ZTree':
            case 'ZTreeSwamp150':
            case 'ZTreeSwamp120':
            case 'ZStumpBurned':
            case 'ZStumpBare':
            case 'ArtiPork':
            case 'Demon1':
            case 'ArtiSuperHealth':
            case 'ArtiTorch':
            case 'Wraith':
            case 'ArtiTeleport':
            case 'ZStumpSwamp1':
            case 'ZStumpSwamp2':
            case 'ZShroomLarge1':
            case 'ZShroomLarge2':
            case 'ZShroomLarge3':
            case 'ZShroomSmall1':
            case 'ZShroomSmall2':
            case 'ZShroomSmall3':
            case 'ZShroomSmall4':
            case 'ZShroomSmall5':
            case 'ZStalagmitePillar':
            case 'ZStalagmiteLarge':
            case 'ZStalagmiteMedium':
            case 'ZStalagmiteSmall':
            case 'ZStalactiteLarge':
            case 'MWeapFrost':
            case 'ZWallTorch':
            case 'ZWallTorchUnlit':
            case 'ZStalactiteMedium':
            case 'ZStalactiteSmall':
            case 'ZMossCeiling1':
            case 'ZMossCeiling2':
            case 'ZSwampVine':
            case 'ZCorpseKabob':
            case 'ZCorpseSleeping':
            case 'ZTombstoneRIP':
            case 'ZTombstoneShane':
            case 'ZTombstoneBigCross':
            case 'ZTombstoneBrianR':
            case 'ZTombstoneCrossCircle':
            case 'ZTombstoneSmallCross':
            case 'ZTombstoneBrianP':
            case 'ZCorpseHanging':
            case 'ZStatueGargoyleGreenTall':
            case 'ZStatueGargoyleBlueTall':
            case 'ZStatueGargoyleGreenShort':
            case 'ZStatueGargoyleBlueShort':
            case 'ZBannerTattered':
            case 'ZTreeLarge1':
            case 'ZTreeLarge2':
            case 'ZTreeGnarled1':
            case 'CrystalVial':
            case 'ArtiHealth':
            case 'ArtiFly':
            case 'ArtiInvulnerability2':
            case 'ArtiDarkServant':
            case 'ZTreeGnarled2':
            case 'ZLog':
            case 'ZStalactiteIceLarge':
            case 'ZStalactiteIceMedium':
            case 'ZStalactiteIceSmall':
            case 'ZStalactiteIceTiny':
            case 'ZStalagmiteIceLarge':
            case 'ZStalagmiteIceMedium':
            case 'ZStalagmiteIceSmall':
            case 'ZStalagmiteIceTiny':
            case 'ZRockBrown1':
            case 'ZRockBrown2':
            case 'ZRockBlack':
            case 'ZRubble1':
            case 'ZRubble2':
            case 'ZRubble3':
            case 'ZVasePillar':
            case 'Pottery1':
            case 'Pottery2':
            case 'Pottery3':
            case 'Centaur':
            case 'ZCorpseLynched':
            case 'ZCorpseLynchedNoHeart':
            case 'ZCorpseSitting':
            case 'BloodPool':
            case 'LittleFly':
            case 'LeafSpawner':
            case 'Bishop':
            case 'CentaurLeader':
            case 'ZTwinedTorch':
            case 'ZTwinedTorchUnlit':
            case 'Bridge':
            case 'ZCandle':
            case 'SerpentLeader':
            case 'Serpent':
            case 'Mana1':
            case 'FWeapHammer':
            case 'Mana2':
            case 'TeleSmoke':
            case 'Dragon':
            case 'SoundWindHexen':
            case '$PolyAnchor':
            case '$PolySpawn':
            case '$PolySpawnCrush':
            case 'ArtiPoisonBag':
            case 'ArtiSpeedBoots':
            case 'ArtiBoostMana':
            case 'Mana3':
            case 'MeshArmor':
            case 'FalconShield':
            case 'PlatinumHelm':
            case 'AmuletOfWarding':
            case 'CWeapFlame':
            case 'FWeapAxe':
            case 'IceGuy':
            case 'KeySteel':
            case 'KeyCave':
            case 'KeyAxe':
            case 'KeyFire':
            case 'KeyEmerald':
            case 'KeyDungeon':
            case 'KeySilver':
            case 'KeyRusted':
            case 'KeyHorn':
            case 'KeySwamp':
            case 'MWeapLightning':
            case 'ArtiBoostArmor':
            case 'ZFireBull':
            case 'ZFireBullUnlit':
            case 'ZStatueGargoyleStripeTall':
            case 'ZStatueGargoyleDarkRedTall':
            case 'ZStatueGargoyleRedTall':
            case 'ZStatueGargoyleTanTall':
            case 'ZStatueGargoyleRustTall':
            case 'ZStatueGargoyleDarkRedShort':
            case 'ZStatueGargoyleRedShort':
            case 'ZStatueGargoyleTanShort':
            case 'ZStatueGargoyleRustShort':
            case 'FireThing':
            case 'BrassTorch':
            case 'TreeDestructible':
            case 'ZChandelierUnlit':
            case 'ZSuitOfArmor':
            case 'ZBell':
            case 'ZBlueCandle':
            case 'ZIronMaiden':
            case 'ZXmasTree':
            case 'ZCauldron':
            case 'ZCauldronUnlit':
            case 'ZChainBit32':
            case 'ZChainBit64':
            case 'ZChainEndHeart':
            case 'ZChainEndHook1':
            case 'ZChainEndHook2':
            case 'ZChainEndSpike':
            case 'ZChainEndSkull':
            case 'Demon2':
            case 'ZBarrel':
            case 'ZShrub1':
            case 'ZShrub2':
            case 'ZBucket':
            case 'ZPoisonShroom':
            case 'KeyCastle':
            case 'TableShit1':
            case 'TableShit2':
            case 'TableShit3':
            case 'TableShit4':
            case 'TableShit5':
            case 'TableShit6':
            case 'TableShit7':
            case 'TableShit8':
            case 'TableShit9':
            case 'TableShit10':
            case 'PuzzSkull':
            case 'PuzzGemBig':
            case 'PuzzGemRed':
            case 'PuzzGemGreen1':
            case 'PuzzGemBlue1':
            case 'PuzzBook1':
            case 'PuzzBook2':
            case 'PuzzGemGreen2':
            case 'PuzzGemBlue2':
            case 'ZWingedStatueNoSkull':
            case 'ZGemPedestal':
            case 'PuzzFlameMask':
            case 'PuzzFWeapon':
            case 'PuzzCWeapon':
            case 'PuzzMWeapon':
            case 'PuzzGear1':
            case 'PuzzGear2':
            case 'PuzzGear3':
            case 'PuzzGear4':
            case '$Player5Start':
            case '$Player6Start':
            case '$Player7Start':
            case '$Player8Start':
            case 'FogSpawner':
            case 'FogPatchSmall':
            case 'FogPatchMedium':
            case 'FogPatchLarge':
            case 'WraithBuried':
            case 'Ettin':
            case 'ArtiTeleportOther':
            case 'FireDemon':
            case 'Heresiarch':
            case 'ThrustFloorDown':
            case 'ThrustFloorUp':
            case 'FighterBoss':
            case 'ClericBoss':
            case 'MageBoss':
            case 'ArtiBlastRadius':
            case 'ArtiHealingRadius':
            case 'Korax':
            case 'BatSpawner':
            case 'FlameSmallTemp':
            case 'FlameSmall':
            case 'FlameLargeTemp':
            case 'FlameLarge':
				e.Replacement = 'UnknownActor';
				break;
		}
	}
}